### ISSUE TITLE
gaRequest Date Format

### ISSUE THREAD

**Issue by andrewgeisler** [andrewgeisler/GAR#2]
gaRequest currently only accepts a date (YYYY-MM-DD) as a character class and will fail if a date class variable is passed to the function.

gaRequest should convert coerce variable to as.character() to address this issue.

**Comment by jdeboer** [comment]
Google Analytics uses two different formats for date information. Dates supplied as date range parameters for a query should be in the format `"%Y-%m-%d"`, whereas the `ga:date` dimension uses the format `"%Y%m%d"` in both a query's resulting output as well as for table filter conditions.

Unlike the `ga:date` dimension, the special `ga:dateOfSession` dimension (that can only be used for segmentation and not as a table output field nor for a table filter condition) accepts dates in the format `"%Y-%m-%d"`.

The [`lubridate`](https://cran.r-project.org/web/packages/lubridate/index.html) package is very helpful for working with dates and times. Its `ymd` function (and other related functions) can be used to automatically parse dates. With this you could write a function to take an object representing a date and return that date in the appropriate character format you need. For example:

``` r
formatDate <- function(date, format = "%Y-%m-%d") {
  format(ymd(date), format = format)
}

formatDate("2015-10-24")
#> [1] "2015-10-24"
formatDate("20151024", format = "%Y%m%d")
#> [1] "20151024"
formatDate("2015/10/24")
#> [1] "2015-10-24"
formatDate(as.Date("2015-10-24"), format = "%Y%m%d")
#> [1] "20151024"
formatDate("2015 Oct 24")
#> [1] "2015-10-24"
formatDate(c("20151022", "20151023", "20151024"))
#> [1] "2015-10-22" "2015-10-23" "2015-10-24"
```

**Comment by andrewgeisler** [comment]
@jdeboer Thanks for the feedback and tip. Initially, my intentional was to simply add a check to make sure that the value being passed to start/end were of the right format but you've given me more to consider in terms of how the dates are used in different circumstances. Thanks!
