### ISSUE TITLE
GAR - HTTR v2 - Test dependancy

### ISSUE THREAD

**Issue by andrewgeisler** [andrewgeisler/GAR#7]

**Comment by andrewgeisler** [comment]
EMAILED HADLEY

Hadley -

I'm having troubling installing httr from github. Well, it installs without error but I get an error when attempting to load it. It's telling me there's a corrupt httr.rdb file. Have you run into anything like this before?

Thanks!

- Andrew Geisler 

Here's the error message:

> install_github('hadley/httr')
Downloading github repo hadley/httr@master
Installing httr
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL \
 '/private/var/folders/cr/qqz4hm7x0914zw54j6bwnr_m0000gp/T/RtmpHfr4pp/devtoolsb1e44d107884/hadley-httr-2a5bec2' \
 --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library' --install-tests 

* installing *source* package ‘httr’ ...
** R
** demo
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (httr)
> require(httr)
Loading required package: httr
Error in get(method, envir = home) : 
 lazy-load database '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/httr/R/httr.rdb' is corrupt
In addition: Warning message:
In get(method, envir = home) : internal error -3 in R_decompress1
>

[--- Commented from Asana.com
#commenter AG
---[aa]

**Comment by jdeboer** [comment]
Hi @andrewgeisler , have you submitted this as an issue on `httr`'s GitHub site? I haven't come across this issue before either, but curious to know more in case I can help in some way.

**Comment by andrewgeisler** [comment]
@jdeboer Oh good grief! I was actually playing around with syncing a project management tool I'm trying out with github. This is something that is actually old that was sitting in that PM system as a task. Looks like the sync created the issue. 

Thanks for the offer but I'm all good!
